### ISSUE TITLE
Not working using docker-compose

### ISSUE THREAD

**Issue by campanom** [garethflowers/docker-svn-server#3]
Hi gareth, I like your image. It is working if i use the docker run command.
But when I try to create container using docker-compose up (using the appropiate yml file) when i execute sh to get inside docker image htpasswd file is missing. It is strange because the image should containt it.
Do you know why it is happening?
Thanks !

**Comment by kefrunk** [comment]
Hi campanom,
I'm asking myself now the same question, how did you solve this finally?
Thanks

**Comment by garethflowers** [comment]
Check out this projects [Wiki](https://github.com/garethflowers/docker-svn-server/wiki) for an [example of a docker-compose file](https://github.com/garethflowers/docker-svn-server/wiki#docker-compose) to use.

**Comment by kefrunk** [comment]
Thanks for the reply Gareth,
I have the server running perfectly and I have no problem creating repos, committing files, etc, but I'm using always urls of type svn://localhost:3690....
What I want to try is to allow http access to the svn server, so that way I can use urls of type http://localhost:HTTP_PORT... 
I think this is configured at web server side, for example if you have apache running, but I'm just using the docker image and it doesn't come with apache or a web server installed, just the svn server at port 3690. So I guess I have to install first the web server
Thanks

**Comment by garethflowers** [comment]
This image only provides access to SVN using the svn protocol.

If you need http access you probably want to be using a different docker image (something like [elleflorio/svn-server](https://hub.docker.com/r/elleflorio/svn-server)).
